apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  type: NodePort        # Change from LoadBalancer to NodePort
  ports:
    - port: 80          # The internal port for the service
      nodePort: 30080    # The external port (choose a port in the range 30000-32767)
  selector:
    app: wordpress
    tier: frontend

